"""fallowers

Revision ID: 258ceb6a7f24
Revises: cc17d1ace1d4
Create Date: 2018-07-21 14:48:57.869204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258ceb6a7f24'
down_revision = 'cc17d1ace1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
